# Generated by Django 4.1.5 on 2023-03-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kismet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Adresse',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Stadt',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Beschreibung',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Hoechstpreis',
            new_name='max_guest',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Mindestpreis',
            new_name='max_price',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Titel',
            new_name='min_price',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='maxGaesteanzahl',
            new_name='title',
        ),
    ]
